Fix observer/unobserve case
w3c/compute-pressure pull request #165
Opened 2022-12-16 08:14 UTC by arskama

fixes #164

2022-12-16 08:15 UTC, arskama commented
Please have a careful look at this. I m not 100% sure of this fix.

2022-12-19 09:05 UTC, kenchris commented
This is not very well defined, it's basically a pseudo instruction.

Behavior might differ depending on when disconnect/unobserve is called. Like after or before it is appended to the active observers list.

2022-12-19 09:16 UTC, kenchris commented
I think the easiest way to fix this is to have some kind of lock (internal promise chain) activated whenever an observe call has not settled, and then only run disconnect and unobserve when the lock is unlocked. Then those would have to become promises, which I guess it probably the only right way to handle this.

Basically when we create a promise in observe() then we add it to an internal list of promises, and we chain disconnect/unobserve on that.

But we need to make sure it works fine with calls like "observe, unobserve, observe" etc. So the unobserve/disconnect calls will need to copy the list of current pending promises

2022-12-19 09:31 UTC, kenchris commented
Maybe this would work:

- store pending observe promises
- disconnect: reject all pending observe promises, but make sure that everything has been removed from "active observer list" - that should be fine 
- unobserve: iterate over the pending promises and reject the ones matching the source. Remove from "active observer list" - might have been added, might not

2022-12-19 12:51 UTC, kenchris requested changes
This won't work according to our discussion

2023-01-04 11:40 UTC, closed without merging