[CRS/202412] changes section from FPWD
w3c/compute-pressure pull request #306
Opened 2024-12-04 11:52 UTC by himorin

as title

not including consideration sections: 251, 247, 219, 216, 207

2024-12-05 09:28 UTC, anssiko approved these changes
Thank you! I note the commit message titles are directly reused here without edits. An improvement might be to adjust wording in a few places, but I'm fine with this too.

@kenchris to check this looks good from an editor's perspective.

2024-12-05 10:15 UTC, kenchris approved these changes

2024-12-05 10:19 UTC, kenchris commented on index.html
> +      <li><a href="https://github.com/w3c/compute-pressure/pull/299">Make ownContributionEstimate experimental (PR #299)</a></li>
This entry and the next are not visible in the non-editors version, so can be removed

2024-12-05 10:19 UTC, kenchris commented on index.html
> +      <li><a href="https://github.com/w3c/compute-pressure/pull/298">Add support for ownContributionEstimate (PR #298)</a></li>
And this one

2024-12-05 10:20 UTC, kenchris requested changes
Let's remove the two entries not visible in the non-editors version

2024-12-11 10:13 UTC, arskama approved these changes
LGTM

2024-12-11 12:16 UTC, anssiko approved these changes

2024-12-11 12:17 UTC, merged